import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#F9F5F0",
        "on-primary": "#F9F5F0",
        "surface-container": "#F1EAE2",
        "tertiary-container": "#fff3d4",
        "secondary-fixed-dim": "#f6be39",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#6D5244",
        "surface-container-low": "#F5EFE7",
        "on-tertiary-container": "#7a5800",
        surface: "#F9F5F0",
        "primary-fixed-dim": "#f0bba0",
        background: "#F9F5F0",
        "on-primary-fixed-variant": "#623e2a",
        "on-secondary-container": "#715300",
        primary: "#4D2C19",
        "on-tertiary-fixed": "#261a00",
        "on-secondary-fixed": "#261a00",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#E9DFD4",
        outline: "#83746D",
        "surface-container-highest": "#E9DFD4",
        "surface-container-high": "#ebe8e3",
        secondary: "#795900",
        "on-tertiary-fixed-variant": "#5c4300",
        "primary-fixed": "#ffdbca",
        "inverse-on-surface": "#f4f0eb",
        "inverse-primary": "#f0bba0",
        "on-primary-container": "#c29279",
        tertiary: "#D4A017",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "outline-variant": "#d5c3bb",
        "inverse-surface": "#31302d",
        "on-surface": "#4D2C19",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#5c4300",
        "secondary-container": "#ffc641",
        "tertiary-fixed-dim": "#B68912",
        "on-primary-fixed": "#301404",
        "surface-dim": "#ddd9d5",
        "secondary-fixed": "#ffdfa0",
        "error-container": "#ffdad6",
        "surface-tint": "#7d553f",
        "tertiary-fixed": "#D4A017",
        "primary-container": "#361E11",
        "on-background": "#4D2C19",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      fontFamily: {
        headline: ["Manrope", "Montserrat", "sans-serif"],
        body: ["Merriweather", "serif"],
        label: ["Montserrat", "sans-serif"],
        serif: ["Noto Serif", "serif"],
        sans: ["Manrope", "Montserrat", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
