import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fdf9f4",
        "on-primary": "#ffffff",
        "surface-container": "#f1ede8",
        "tertiary-container": "#453100",
        "secondary-fixed-dim": "#f6be39",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#51443e",
        "surface-container-low": "#f7f3ee",
        "on-tertiary-container": "#c79501",
        surface: "#fdf9f4",
        "primary-fixed-dim": "#f0bba0",
        background: "#fdf9f4",
        "on-primary-fixed-variant": "#623e2a",
        "on-secondary-container": "#715300",
        primary: "#341706",
        "on-tertiary-fixed": "#261a00",
        "on-secondary-fixed": "#261a00",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#e6e2dd",
        outline: "#83746d",
        "surface-container-highest": "#e6e2dd",
        "surface-container-high": "#ebe8e3",
        secondary: "#795900",
        "on-tertiary-fixed-variant": "#5c4300",
        "primary-fixed": "#ffdbca",
        "inverse-on-surface": "#f4f0eb",
        "inverse-primary": "#f0bba0",
        "on-primary-container": "#c29279",
        tertiary: "#2a1d00",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "outline-variant": "#d5c3bb",
        "inverse-surface": "#31302d",
        "on-surface": "#1c1c19",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#5c4300",
        "secondary-container": "#ffc641",
        "tertiary-fixed-dim": "#f6be39",
        "on-primary-fixed": "#301404",
        "surface-dim": "#ddd9d5",
        "secondary-fixed": "#ffdfa0",
        "error-container": "#ffdad6",
        "surface-tint": "#7d553f",
        "tertiary-fixed": "#ffdfa0",
        "primary-container": "#4d2c19",
        "on-background": "#1c1c19",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        serif: ["Noto Serif", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
