export type Section =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string; author?: string }
  | { type: "callout"; title: string; text: string };

export type Article = {
  slug: string;
  title: string;
  category: "Basics" | "Brewing" | "Roast" | "Buying" | "Local";
  excerpt: string;
  readingTime: string;
  publishedAt: string;
  image: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
  body: Section[];
  related: string[];
};

const IMG =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuC-mgzdszeDV-ADPnt08LksEtq5jHo_pZiXrnzVNy7faF7CAvNwCIqw0tZ2ylgRbHNuI-cdksgJ49bjfH36AYZerX9qRPq7kE2svCJ2KsLCMhI2k4Dc50D2D5FEGms1FJKDbeS75aSghLNY7Dop_dxhV5e-766gOscbYVVzn4qpX1rtPcumcDu7hr6OQeoiBzbRrze7HIkmFAM9YOYzQFzRF1wR3U1Ec53bS5Aj9xRlWvn7KxLIHJL79Wy6T8BFR47-ulGO1PjIJKEL";

export const articles: Article[] = [
  {
    slug: "what-is-specialty-coffee",
    title: "Was ist Specialty Coffee?",
    category: "Basics",
    excerpt: "Specialty Coffee ist mehr als ein Marketing-Begriff. Erfahre was die SCA-Definition bedeutet und warum 80+ Punkte alles ändern.",
    readingTime: "5 Min",
    publishedAt: "2025-04-15",
    image: IMG,
    seoTitle: "Was ist Specialty Coffee? — Definition, Bedeutung, Unterschied",
    seoDescription: "Specialty Coffee einfach erklärt: SCA-Bewertung ab 80 Punkten, Direct Trade, Single Origin. Der komplette Guide für Schweizer Genießer.",
    keywords: ["specialty coffee", "was ist specialty coffee", "sca cupping", "single origin", "direct trade"],
    body: [
      { type: "p", text: "Specialty Coffee ist die Champions League des Kaffees. Während handelsüblicher Kaffee oft anonyme Mischungen unklarer Herkunft enthält, wird Specialty Coffee unter strengen Kriterien bewertet — und das nach einem internationalen Standard." },
      { type: "h2", text: "Die SCA-Definition: 80+ Punkte" },
      { type: "p", text: "Die Specialty Coffee Association (SCA) hat ein 100-Punkte-System etabliert. Nur Kaffees, die im Cupping (sensorische Bewertung) mindestens 80 Punkte erreichen, dürfen sich Specialty Coffee nennen. Bewertet werden Aroma, Säure, Körper, Süße, Balance und Klarheit der Tasse." },
      { type: "h2", text: "Was unterscheidet Specialty von Industrie-Kaffee?" },
      { type: "ul", items: [
        "Single Origin — exakte Farm, exakte Lagerhöhe, exakte Varietät",
        "Direct Trade — Röster kennt den Bauern persönlich, faire Preise weit über Fairtrade-Niveau",
        "Sortenreinheit — keine Robusta-Beimischung, oft sortenreine Heirloom-Varietäten",
        "Aufbereitung — Washed, Honey oder Natural Process, alles transparent",
        "Röstfrische — Kaffee wird erst nach Bestellung geröstet, nicht monatelang gelagert",
      ]},
      { type: "h2", text: "Warum kostet Specialty Coffee mehr?" },
      { type: "p", text: "Ein 250g-Beutel Specialty Coffee kostet zwischen CHF 18 und CHF 50. Der Preis spiegelt die Qualität wider: Bauern erhalten oft das 3- bis 5-fache des Weltmarktpreises. Das macht den Unterschied zwischen einer austauschbaren Tasse und einem Erlebnis." },
      { type: "callout", title: "Coffee Selection Standard", text: "Alle Kaffees in unserem Sortiment haben mindestens 84 Punkte im SCA-Cupping. Direct Trade ist nicht Marketing, sondern Praxis." },
      { type: "p", text: "Bereit, deinen Specialty Coffee zu finden? Mach das 12-Fragen-Quiz und wir matchen dich mit dem Kaffee, der zu deinem Geschmackstyp passt." },
    ],
    related: ["how-to-choose-coffee", "coffee-flavor-wheel", "best-coffee-switzerland"],
  },
  {
    slug: "how-to-choose-coffee",
    title: "Wie wähle ich den richtigen Kaffee?",
    category: "Buying",
    excerpt: "Brühmethode, Geschmacksprofil, Röstgrad — die drei Faktoren, die deine Kaffeewahl bestimmen sollten.",
    readingTime: "4 Min",
    publishedAt: "2025-04-10",
    image: IMG,
    seoTitle: "Kaffee auswählen — der ultimative Guide für Specialty Coffee",
    seoDescription: "Wie wähle ich den richtigen Kaffee? Brühmethode, Geschmacksprofil, Röstgrad — der Schweizer Sommelier-Guide.",
    keywords: ["kaffee auswählen", "richtigen kaffee finden", "specialty coffee guide", "kaffee kaufen tipps"],
    body: [
      { type: "p", text: "Vor dem ersten Cappuccino kommt die richtige Bohne. Aber wie wählst du aus tausenden Specialty Coffees genau den, der zu dir passt? Drei Fragen entscheiden alles." },
      { type: "h2", text: "1. Wie bereitest du Kaffee zu?" },
      { type: "p", text: "Die Brühmethode bestimmt den passenden Mahlgrad und Röstgrad. Espresso braucht eine andere Bohne als V60." },
      { type: "ul", items: [
        "Vollautomat → mittel geröstete Espresso-Blends, gut entwickelt",
        "Siebträger → italienische Espresso-Röstungen, hohe Crema",
        "V60 / Filter / Aeropress → helle Single Origins mit floralen Noten",
        "French Press → mittel-dunkle Röstungen mit Körper",
        "Moka Pot → klassische italienische Espresso-Bohnen",
      ]},
      { type: "h2", text: "2. Welches Aromen-Profil magst du?" },
      { type: "p", text: "Specialty Coffee ist kein einheitlicher Geschmack. Manche Bohnen schmecken nach Erdbeere und Bergamotte, andere nach Kakao und Tabak. Frage dich: was trinkst du sonst noch? Wein-Liebhaber bevorzugen oft fruchtige helle Röstungen, Whisky-Trinker tendieren zu erdigen, würzigen Profilen." },
      { type: "h2", text: "3. Wie sensibel ist dein Magen?" },
      { type: "p", text: "Helle Röstungen haben mehr Säure — gut für die Geschmackswahrnehmung, schlecht bei empfindlichem Magen. Dunkler geröstete Bohnen oder magenfreundliche Sumatra-Sorten sind die Lösung." },
      { type: "callout", title: "Shortcut: Mach das Quiz", text: "Statt selbst zu rätseln: Unser 12-Fragen-Quiz kombiniert alle drei Faktoren und matcht dich präzise mit deinem Geschmackstyp." },
    ],
    related: ["light-vs-dark-roast", "coffee-acidity-explained", "what-is-specialty-coffee"],
  },
  {
    slug: "coffee-flavor-wheel",
    title: "Das Coffee Flavor Wheel — Aromen verstehen",
    category: "Basics",
    excerpt: "Von Beere bis Tabak: Wie du Kaffee-Aromen systematisch erkennst — und endlich die Notes auf den Verpackungen verstehst.",
    readingTime: "6 Min",
    publishedAt: "2025-04-05",
    image: IMG,
    seoTitle: "Coffee Flavor Wheel — Aromen-Wheel erklärt | Coffee Selection",
    seoDescription: "Das SCA Flavor Wheel macht Kaffee-Aromen systematisch erkennbar. Von Beere zu Tabak — der komplette Sensorik-Guide.",
    keywords: ["coffee flavor wheel", "kaffee aromen", "sca flavor wheel", "tasting notes kaffee", "kaffee verkosten"],
    body: [
      { type: "p", text: "Wenn auf einer Kaffee-Verpackung 'Bergamotte, Jasmin, weißer Pfirsich' steht — was bedeutet das wirklich? Das Coffee Flavor Wheel der SCA bietet eine Sprache für genau diese Frage." },
      { type: "h2", text: "Die 9 Hauptkategorien" },
      { type: "ol", items: [
        "Floral — Jasmin, Rose, Bergamotte, Hibiskus",
        "Fruity — Beeren, Zitrus, Tropisch, Trockenfrüchte",
        "Sour/Fermented — Wein-Note, fermentierte Aromen",
        "Green/Vegetative — Heu, frisches Gras, Pflanzlich",
        "Other — Papier, Chemisch (negativ)",
        "Roasted — Pfeife, Tabak, Verbrannt",
        "Spices — Pfeffer, Anis, Nelke, Zimt",
        "Nutty/Cocoa — Mandel, Haselnuss, Schokolade, Kakao",
        "Sweet — Honig, Vanille, Karamell, Brauner Zucker",
      ]},
      { type: "h2", text: "Warum verschiedene Bohnen unterschiedliche Aromen haben" },
      { type: "p", text: "Das Aromen-Profil hängt von vier Faktoren ab: der Varietät (Bourbon, Geisha, Heirloom), der Anbauregion (Höhe, Klima), der Aufbereitung (Washed, Natural, Honey) und der Röstung (hell vs. dunkel)." },
      { type: "h2", text: "Wie du selbst Aromen erkennst" },
      { type: "ul", items: [
        "Riechen vor dem Trinken — die Nase erkennt 10-mal feiner als die Zunge",
        "Tasse leicht abkühlen lassen — Aromen kommen besser bei 60–65°C",
        "Zwei oder drei kleine Schlucke — der erste ist Reset, dann erkennst du mehr",
        "Mit anderen Lebensmitteln vergleichen — die Erdbeere im Kaffee, ist das Walderdbeere oder Garten? Das schult deine Sensorik",
      ]},
      { type: "callout", title: "Praktischer Tipp", text: "Drucke dir das SCA Flavor Wheel aus und hänge es neben deine Espresso-Maschine. In zwei Wochen erkennst du Aromen, die du vorher nie wahrgenommen hast." },
    ],
    related: ["coffee-acidity-explained", "what-is-specialty-coffee", "how-to-brew-v60"],
  },
  {
    slug: "espresso-vs-filter",
    title: "Espresso vs. Filterkaffee — was ist der Unterschied?",
    category: "Brewing",
    excerpt: "Mehr als nur Druck vs. Schwerkraft: Warum Espresso und Filter zwei völlig verschiedene Welten sind.",
    readingTime: "4 Min",
    publishedAt: "2025-03-28",
    image: IMG,
    seoTitle: "Espresso vs. Filterkaffee — Unterschied einfach erklärt",
    seoDescription: "Espresso vs. Filter: Druck, Mahlgrad, Aroma, Koffein. Was der Unterschied wirklich ausmacht und welcher Kaffee sich für welche Methode eignet.",
    keywords: ["espresso vs filterkaffee", "filter vs espresso", "unterschied espresso filter", "espresso filterkaffee"],
    body: [
      { type: "p", text: "Espresso und Filterkaffee — beide sind Kaffee, aber das Endergebnis könnte unterschiedlicher kaum sein. Der Unterschied liegt nicht nur im Druck, sondern in einer ganzen Philosophie." },
      { type: "h2", text: "Die mechanischen Unterschiede" },
      { type: "ul", items: [
        "Druck: Espresso 9 bar, Filter 0 bar (nur Schwerkraft)",
        "Brühzeit: Espresso 25–30 Sekunden, Filter 3–4 Minuten",
        "Mahlgrad: Espresso fein wie Puderzucker, Filter mittel-grob",
        "Wassermenge: Espresso 30 ml, Filter 250 ml",
        "Verhältnis Bohne:Wasser: Espresso 1:2, Filter 1:16",
      ]},
      { type: "h2", text: "Geschmackliche Konsequenzen" },
      { type: "p", text: "Espresso konzentriert alles: Säure, Süße, Bitterkeit, Körper. Eine kleine Tasse mit hoher Intensität. Filter dagegen bringt Klarheit — du schmeckst feine florale Noten, die im Espresso untergehen würden. Eine helle Äthiopier-Röstung wirkt im Filter wie eine Symphonie, im Espresso wie ein lauter Akkord." },
      { type: "h2", text: "Welche Bohne für welche Methode?" },
      { type: "ul", items: [
        "Espresso bevorzugt: mittlere bis dunkle Röstungen, Brasilien-Naturals, italienische Blends",
        "Filter bevorzugt: helle Röstungen, gewaschene Äthiopier, Kenya AA, Geisha",
        "Universal-Bohnen: Costa Rica Honey, Colombia Mittelröstung",
      ]},
      { type: "callout", title: "Pro-Tipp", text: "Eine Bohne, die im Espresso brillant wirkt, kann im Filter flach schmecken — und umgekehrt. Frag den Röster oder lies die Empfehlung auf der Verpackung." },
    ],
    related: ["how-to-brew-v60", "how-to-brew-espresso", "best-coffee-for-full-automatic"],
  },
  {
    slug: "light-vs-dark-roast",
    title: "Helle vs. dunkle Röstung — der Unterschied",
    category: "Roast",
    excerpt: "Mehr Koffein bei hell oder dunkel? Warum dunkel nicht stärker schmeckt — und wie du die richtige Röststufe findest.",
    readingTime: "4 Min",
    publishedAt: "2025-03-20",
    image: IMG,
    seoTitle: "Helle vs. dunkle Röstung — Unterschied & welche ist besser?",
    seoDescription: "Hell oder dunkel? Mythen über Koffein-Gehalt, Röstgrade erklärt, Geschmacksunterschiede und welche Röstung zu deinem Geschmackstyp passt.",
    keywords: ["helle dunkle röstung", "hell vs dunkel kaffee", "röstgrad kaffee", "light roast vs dark roast"],
    body: [
      { type: "p", text: "Glaubst du, dunkler gerösteter Kaffee hat mehr Koffein? Falsch. Glaubst du, helle Röstungen sind säuerlich und unangenehm? Auch falsch. Hier sind die Fakten." },
      { type: "h2", text: "Was bei der Röstung passiert" },
      { type: "p", text: "Eine grüne Kaffeebohne enthält Säuren, Zucker, Aromen-Vorstufen. Beim Rösten zwischen 195°C und 240°C entstehen über 800 verschiedene Aromen. Je länger geröstet wird, desto mehr Bitterstoffe entstehen — und desto mehr Säuren werden abgebaut." },
      { type: "h2", text: "Helle Röstung (195–210°C)" },
      { type: "ul", items: [
        "Lebendige Säure, fruchtige und florale Aromen",
        "Origin-Charakter dominiert (Äthiopien schmeckt wie Äthiopien)",
        "Höhere Konzentration an Antioxidantien",
        "Etwas mehr Koffein pro Volumen",
        "Ideal für: Filter, V60, Aeropress, Pour Over",
      ]},
      { type: "h2", text: "Dunkle Röstung (220–240°C)" },
      { type: "ul", items: [
        "Schokolade, Karamell, Tabak, weniger Säure",
        "Röstaromen dominieren über Origin-Charakter",
        "Volle, ölige Crema im Espresso",
        "Magenfreundlicher (weniger Säure)",
        "Ideal für: Espresso, Moka Pot, French Press",
      ]},
      { type: "callout", title: "Mythen-Check", text: "Dunkler Kaffee = mehr Koffein? Falsch. Bei gleicher Bohnenmenge enthält helle Röstung sogar leicht mehr Koffein, weil die Bohnen weniger an Masse verloren haben." },
      { type: "p", text: "Die richtige Röstung ist eine persönliche Entscheidung. Bist du Espresso-Enthusiast oder Filter-Fan? Genau das fragt unser Quiz." },
    ],
    related: ["coffee-acidity-explained", "espresso-vs-filter", "how-to-choose-coffee"],
  },
  {
    slug: "coffee-acidity-explained",
    title: "Säure im Kaffee — verstehen, nicht fürchten",
    category: "Roast",
    excerpt: "Säure ist nicht gleich sauer. Warum lebendige Säure das Markenzeichen guter Specialty Coffees ist — und was tun bei empfindlichem Magen.",
    readingTime: "5 Min",
    publishedAt: "2025-03-15",
    image: IMG,
    seoTitle: "Säure im Kaffee erklärt — Magenfreundlicher Specialty Coffee",
    seoDescription: "Was bedeutet Säure im Kaffee? Welche Bohnen sind säurearm? Komplette Erklärung mit Tipps für magenempfindliche Genießer.",
    keywords: ["kaffee säure", "säurearmer kaffee", "magenfreundlicher kaffee", "kaffee säuregehalt"],
    body: [
      { type: "p", text: "'Mein Kaffee ist mir zu sauer.' — wenn du das schon mal gesagt hast, gibt es zwei Möglichkeiten: entweder hast du wirklich saures, schlecht zubereitetes Brühzeug erwischt, oder du verwechselst die belebende Säure (Acidity) eines Specialty Coffees mit der unangenehmen Sauerheit (Sourness) einer schlechten Tasse." },
      { type: "h2", text: "Acidity vs. Sourness" },
      { type: "p", text: "Acidity ist eine positive Eigenschaft: lebendig, klar, hell, fruchtig — wie Bergamotte oder Limette. Sourness dagegen ist ein Defekt: stechend, unangenehm, verursacht oft durch Unter-Extraktion (zu kurze Brühzeit) oder schlechte Aufbereitung." },
      { type: "h2", text: "Was beeinflusst die Säure?" },
      { type: "ul", items: [
        "Anbaulage: Hochlagen → mehr Säure (langsamere Reifung = mehr Aromen-Komplexität)",
        "Origin: Äthiopien und Kenia haben hohe Säure, Sumatra niedrige",
        "Röstgrad: heller = mehr Säure, dunkler = weniger",
        "Aufbereitung: Washed → klare Säure, Natural → mildere Säure",
        "Brühmethode: V60 betont Säure, French Press dämpft sie",
      ]},
      { type: "h2", text: "Was tun bei empfindlichem Magen?" },
      { type: "ul", items: [
        "Sumatra Mandheling oder Brasilien Naturals — von Natur aus säurearm",
        "Mittlere bis dunkle Röstungen wählen",
        "Cold Brew zubereiten — extrahiert weniger Säure",
        "Mit Milch trinken — Kalzium neutralisiert teilweise die Säure",
        "Auf nüchternen Magen vermeiden",
      ]},
      { type: "callout", title: "Coffee Selection Empfehlung", text: "Für sensible Mägen: Sumatra Mandheling von Stoll Kaffee oder Brasil Natural Decaf von Miro Coffee. Beide sehr mild." },
    ],
    related: ["light-vs-dark-roast", "how-to-choose-coffee", "what-is-specialty-coffee"],
  },
  {
    slug: "best-coffee-for-full-automatic",
    title: "Der beste Kaffee für deinen Vollautomaten",
    category: "Brewing",
    excerpt: "Vollautomat = günstiger Filterkaffee? Falsch. Welche Bohnen wirklich passen und warum die meisten Empfehlungen Quatsch sind.",
    readingTime: "5 Min",
    publishedAt: "2025-03-08",
    image: IMG,
    seoTitle: "Bester Kaffee für Vollautomaten — Specialty Coffee Empfehlungen",
    seoDescription: "Vollautomat-Kaffee einfach erklärt: Welcher Röstgrad, welche Bohnen, welche Mahlgrade. Schweizer Specialty-Empfehlungen für Jura, DeLonghi & Co.",
    keywords: ["bester kaffee vollautomat", "vollautomat kaffee", "specialty coffee vollautomat", "kaffeebohnen vollautomat"],
    body: [
      { type: "p", text: "90% der Schweizer Haushalte mit Kaffeemaschine haben einen Vollautomaten. Trotzdem werden ihnen meist die schlechtesten Bohnen verkauft — generische Espresso-Mischungen aus dem Supermarkt. Es geht besser." },
      { type: "h2", text: "Wie ein Vollautomat brüht" },
      { type: "p", text: "Vollautomaten arbeiten mit Druck (8–15 bar) und kürzeren Brühzeiten als Siebträger. Die Maschine hat begrenzte Kontrolle über Mahlgrad-Feinheiten und Wassertemperatur. Das bedeutet: die Bohne muss 'verzeihend' sein." },
      { type: "h2", text: "Was Vollautomaten gut können" },
      { type: "ul", items: [
        "Mittel- bis dunkle Röstungen mit ölfreier Oberfläche",
        "Espresso-Blends mit hohem Brasilien-Anteil (verzeihende Charakteristik)",
        "Bohnen mit gut entwickelten Karamell- und Schokoladennoten",
        "Etwas weniger Säure als bei reinem Filterkaffee",
      ]},
      { type: "h2", text: "Was sie schlecht können" },
      { type: "ul", items: [
        "Sehr ölige Bohnen (verstopfen das Mahlwerk)",
        "Sehr helle Röstungen (Aromen kommen nicht zur Geltung)",
        "Reine Robusta-Mischungen (geschmacklich flach)",
        "Sehr fein gemahlene Espresso-Bohnen (verstopfen)",
      ]},
      { type: "callout", title: "Coffee Selection Empfehlungen für Vollautomaten", text: "Brasil Cerrado (Miro Coffee), Honduras Marcala (Stoll Kaffee), Espresso Tradizionale (Stoll Kaffee). Alle drei sind getestet auf Jura, DeLonghi, Krups, Saeco und Melitta." },
      { type: "p", text: "Vermeide: ölige italienische Espressi vom Supermarkt — sie sind oft mit Robusta gestreckt und schaden langfristig der Maschine." },
    ],
    related: ["espresso-vs-filter", "how-to-choose-coffee", "best-coffee-switzerland"],
  },
  {
    slug: "how-to-brew-v60",
    title: "V60 Pour Over — die perfekte Tasse",
    category: "Brewing",
    excerpt: "Schritt-für-Schritt: Wie du mit dem Hario V60 einen Filterkaffee brühst, der wie ein Top-Café schmeckt. Mit Rezept.",
    readingTime: "6 Min",
    publishedAt: "2025-03-01",
    image: IMG,
    seoTitle: "V60 brühen — Anleitung Pour Over für Specialty Coffee",
    seoDescription: "Wie brüht man V60 Filterkaffee? Komplettes Rezept: Mahlgrad, Wassertemperatur, Pour-Technik. Schritt-für-Schritt-Anleitung.",
    keywords: ["v60 brühen", "v60 anleitung", "pour over kaffee", "hario v60 rezept", "filterkaffee anleitung"],
    body: [
      { type: "p", text: "Der Hario V60 ist der populärste Pour-Over-Cone der Welt. Mit einer hellen Äthiopier-Bohne und 4 Minuten Aufmerksamkeit brühst du eine Tasse, die in jedem Berliner Specialty-Café für CHF 8 verkauft wird." },
      { type: "h2", text: "Was du brauchst" },
      { type: "ul", items: [
        "Hario V60-Cone (Größe 02 für 1–4 Tassen)",
        "Passende V60-Filterpapiere",
        "Frische Specialty-Bohnen, mittel-grob gemahlen (wie Sand)",
        "Waage mit 0.1g-Genauigkeit",
        "Wasserkocher mit Schwanenhals oder Gooseneck",
        "Timer",
      ]},
      { type: "h2", text: "Das Rezept (300ml Tasse)" },
      { type: "ol", items: [
        "Filter einlegen, mit heißem Wasser spülen (entfernt Papiergeschmack, wärmt Cone)",
        "18g Kaffee einwiegen, gleichmäßig verteilen",
        "Wasser auf 92–94°C erhitzen",
        "0:00 Bloom: 50g Wasser zugießen, kreisende Bewegung, 30 Sekunden warten",
        "0:30 Erste Phase: in 30 Sekunden auf 150g Gesamt aufgießen",
        "1:00 Zweite Phase: auf 250g aufgießen (innerhalb von 30 Sekunden)",
        "1:30 Letzter Pour: auf 300g auffüllen",
        "Gesamtzeit sollte 3:30 bis 4:00 sein",
      ]},
      { type: "h2", text: "Häufige Fehler" },
      { type: "ul", items: [
        "Mahlgrad zu fein → Brühzeit über 5 Min, schmeckt bitter",
        "Mahlgrad zu grob → Brühzeit unter 3 Min, schmeckt wässrig",
        "Wasser zu heiß → über-extrahiert, bitter",
        "Wasser zu kalt → unter-extrahiert, sauer und flach",
      ]},
      { type: "callout", title: "Kaffee-Empfehlung für V60", text: "Ethiopia Yirgacheffe, Kenya AA, Costa Rica Honey — alles helle Single Origins. Vermeide italienische Espresso-Blends im V60." },
    ],
    related: ["how-to-brew-espresso", "espresso-vs-filter", "what-is-specialty-coffee"],
  },
  {
    slug: "how-to-brew-espresso",
    title: "Espresso brühen — die 25-Sekunden-Regel",
    category: "Brewing",
    excerpt: "Mahlgrad, Tampendruck, Brühzeit: Die drei Stellschrauben für den perfekten Espresso. Mit Rezept und Troubleshooting.",
    readingTime: "5 Min",
    publishedAt: "2025-02-22",
    image: IMG,
    seoTitle: "Espresso brühen — perfekter Espresso aus dem Siebträger",
    seoDescription: "Wie brüht man perfekten Espresso? Mahlgrad, Druck, Brühzeit. Schritt-für-Schritt-Anleitung mit Troubleshooting.",
    keywords: ["espresso brühen", "siebträger anleitung", "espresso rezept", "perfekter espresso"],
    body: [
      { type: "p", text: "Ein perfekter Espresso ist ein 25-Sekunden-Wunder. 9 bar Druck, 9 Gramm Bohne, 30 ml Crema-getränktes Konzentrat. Klingt einfach, ist es nicht." },
      { type: "h2", text: "Das 1:2-Brewing-Ratio" },
      { type: "p", text: "Die heutige Standard-Regel: 18g Bohne ergeben 36g Espresso (Doppelter Espresso). Das nennt sich Brewing Ratio 1:2 — der heilige Gral für moderne Espresso-Bars." },
      { type: "h2", text: "Schritt für Schritt" },
      { type: "ol", items: [
        "Maschine aufheizen (Siebträger und Tasse 15 Min vorwärmen)",
        "18g Bohnen frisch mahlen, fein wie Puderzucker",
        "Gleichmäßig im Siebträger verteilen, mit 15kg Druck tampen",
        "Sofort einspannen und brühen",
        "Crema-Bildung beobachten: 2–4 Sekunden Vorlauf, dann steady stream",
        "Stopp nach 25–30 Sekunden bei 36g Output",
      ]},
      { type: "h2", text: "Troubleshooting" },
      { type: "ul", items: [
        "Espresso läuft zu schnell durch (unter 20 Sek) → Mahlgrad feiner",
        "Espresso läuft zu langsam (über 35 Sek) → Mahlgrad gröber",
        "Schmeckt bitter → über-extrahiert, kürzer brühen oder gröber mahlen",
        "Schmeckt sauer/dünn → unter-extrahiert, länger brühen oder feiner mahlen",
        "Wenig Crema → Bohnen zu alt (>4 Wochen nach Röstung)",
      ]},
      { type: "callout", title: "Pro-Tipp", text: "Frische Bohnen sind alles. Eine 8 Wochen alte Espresso-Mischung kann nicht gut schmecken, egal wie gut deine Maschine ist. Specialty Coffee zeigt Roast Date — kaufe nichts älter als 4 Wochen." },
    ],
    related: ["how-to-brew-v60", "espresso-vs-filter", "best-coffee-for-full-automatic"],
  },
  {
    slug: "how-coffee-subscriptions-work",
    title: "Wie funktioniert ein Kaffee-Abo?",
    category: "Buying",
    excerpt: "Discovery vs. Klassisch, Lieferintervalle, Pausieren — der komplette Guide für Schweizer Coffee-Abonnements.",
    readingTime: "4 Min",
    publishedAt: "2025-02-15",
    image: IMG,
    seoTitle: "Kaffee-Abo erklärt — wie funktionieren Coffee Subscriptions?",
    seoDescription: "Kaffee-Abonnement Schweiz: Wie funktioniert es, was kostet es, kann ich pausieren? Der komplette Guide für Specialty Coffee Subscriptions.",
    keywords: ["kaffee abo", "coffee subscription", "kaffeeabonnement schweiz", "specialty coffee abo"],
    body: [
      { type: "p", text: "Ein Kaffee-Abo bringt regelmäßig frischen Specialty Coffee zu dir nach Hause. Klingt simpel — aber zwischen den Anbietern gibt es enorme Unterschiede." },
      { type: "h2", text: "Discovery vs. Klassisch" },
      { type: "ul", items: [
        "Discovery Abo: Jeden Monat zwei verschiedene Kaffees, kuratiert nach deinem Geschmackstyp. Du entdeckst Neues.",
        "Klassisches Abo: Immer derselbe Kaffee. Konstant, verlässlich, nie Überraschungen.",
        "Empfehlung: Discovery für Entdecker, Klassisch für Gewohnheitstrinker.",
      ]},
      { type: "h2", text: "Lieferintervalle" },
      { type: "ul", items: [
        "Wöchentlich — für Vieltrinker (4+ Tassen pro Tag)",
        "Alle 2 Wochen — beliebteste Wahl, ideal für 2–3 Tassen pro Tag",
        "Monatlich — Standard, ideal für 1–2 Tassen pro Tag",
        "Alle 6 Wochen — für Genießer am Wochenende",
      ]},
      { type: "h2", text: "Worauf du achten solltest" },
      { type: "ul", items: [
        "Mindestlaufzeit? Bei guten Anbietern: keine.",
        "Pausieren möglich? Sollte mit einem Klick gehen.",
        "Versandkosten? Bei Specialty Coffee Selection ab CHF 100 kostenlos.",
        "Frische? Erst nach Bestellung geröstet, geliefert in 2–4 Tagen.",
        "Algorithmus? Wenn er aus deinem Quiz lernt, passen die Empfehlungen besser über Zeit.",
      ]},
      { type: "callout", title: "Coffee Selection Discovery Abo", text: "Ab CHF 24 pro Lieferung, 15% Rabatt gegenüber Einzelbestellung, jederzeit pausierbar. Quiz machen → Geschmackstyp finden → Abo starten." },
    ],
    related: ["how-to-choose-coffee", "what-is-specialty-coffee", "best-coffee-switzerland"],
  },
  {
    slug: "best-coffee-switzerland",
    title: "Der beste Kaffee in der Schweiz — 2025",
    category: "Local",
    excerpt: "Die 8 besten Schweizer Specialty-Röstereien im Überblick. Wer macht den besten Espresso? Welche Bohnen lohnen sich wirklich?",
    readingTime: "7 Min",
    publishedAt: "2025-02-08",
    image: IMG,
    seoTitle: "Beste Kaffee Schweiz 2025 — Top Specialty Coffee Röster",
    seoDescription: "Die besten Schweizer Specialty Coffee Röstereien 2025: Miro Coffee, Vertical, Stoll, La Cabra, Sweven. Komplette Übersicht & Empfehlungen.",
    keywords: ["bester kaffee schweiz", "specialty coffee schweiz", "schweizer kaffeeröster", "beste rösterei schweiz"],
    body: [
      { type: "p", text: "Die Schweiz hat eine erstaunliche Specialty-Coffee-Szene. Mit über 16 Top-Röstereien zwischen Genf und St. Gallen ist die Auswahl überwältigend. Hier sind die acht, die wirklich zählen." },
      { type: "h2", text: "Deutschschweiz" },
      { type: "h3", text: "Miro Coffee Roasters (Zürich)" },
      { type: "p", text: "Pioniere des nordischen Röststils. Spezialität: helle, äthiopische Single Origins mit floralen Noten. Direct Trade, Bio-zertifiziert. Stärke: V60 und Filter." },
      { type: "h3", text: "Atelier Espresso (Zürich)" },
      { type: "p", text: "Italienische Espresso-Tradition seit 2014. Marco Ricci röstet im klassischen italienischen Stil — dunkel, ölig, mit ausgeprägten Schokoladennoten. Beliefert die meisten Top-Hotels in Zürich." },
      { type: "h3", text: "Stoll Kaffee (Luzern)" },
      { type: "p", text: "Familienrösterei seit 1928. Magenfreundliche Mittelröstungen und indonesische Spezialitäten. Vier Generationen Erfahrung in jeder Tasse." },
      { type: "h2", text: "Bern & Innerschweiz" },
      { type: "h3", text: "Vertical Coffee (Bern)" },
      { type: "p", text: "Hochlagen-Spezialist. Bio-Single-Origins aus Costa Rica, Kenia, Kolumbien. Honey Process und Washed Lots dominieren das Sortiment." },
      { type: "h2", text: "Nordwestschweiz" },
      { type: "h3", text: "La Cabra Schweiz (Basel)" },
      { type: "p", text: "Schweizer Ableger der dänischen Kult-Rösterei. Anaerobic Naturals, Carbonic Maceration, Pink Bourbon. Für Entdecker, die experimentelle Aufbereitungen lieben." },
      { type: "h3", text: "Boncourt (Basel)" },
      { type: "p", text: "Traditionsrösterei seit 1955. Magenfreundliche Mittelröstungen, indonesische Bohnen wie Java Estate und Sumatra Mandheling." },
      { type: "h2", text: "Romandie" },
      { type: "h3", text: "Sweven Coffee (Genf)" },
      { type: "p", text: "Highend-Spezialist für Geisha und Yemen Mokha. Hochlagen-Mikrolots aus Cup-of-Excellence-Auktionen. Wenn Geld keine Rolle spielt: hier suchen." },
      { type: "callout", title: "Coffee Selection bringt sie alle zu dir", text: "Wir kuratieren aus allen 16 Top-Schweizer Röstereien. Mach das Quiz, finde deinen Match, lass dich überraschen — alles in einem Abo." },
    ],
    related: ["how-coffee-subscriptions-work", "what-is-specialty-coffee", "how-to-choose-coffee"],
  },
];

export const articleBySlug = (slug: string) => articles.find((a) => a.slug === slug);
export const articlesByCategory = (cat: string) => articles.filter((a) => a.category === cat);
export const allCategories = Array.from(new Set(articles.map((a) => a.category)));
